/* ==========================================================================
   Ember & Crumb — catalogue + studio ingredients
   Every entry carries an Arabic twin (ar_*) and a colour used both for the
   picker swatch and for the live preview drawing.
   Prices are Kuwaiti dinar (KD), quoted to three decimals / fils.
   ========================================================================== */

/* ======================================================== BREW METHODS */
const BREW_METHODS = [
  { id:'espresso',   name:'Espresso Machine', ar:'ماكينة إسبريسو',
    grind:'Fine',            ar_grind:'ناعم',
    recipe:'18 g in, 36 g out, 28 seconds', ar_recipe:'١٨ غم داخل، ٣٦ غم خارج، ٢٨ ثانية' },
  { id:'turkish',    name:'Turkish / Qahwa Pot', ar:'دلة أو ركوة',
    grind:'Powder fine',     ar_grind:'ناعم كالبودرة',
    recipe:'1 heaped tsp per 60 ml, brought up three times', ar_recipe:'ملعقة صغيرة لكل ٦٠ مل، تُرفع ثلاث مرات' },
  { id:'v60',        name:'Pour-over / V60',  ar:'تقطير يدوي V60',
    grind:'Medium-fine',     ar_grind:'متوسط النعومة',
    recipe:'15 g to 250 g water, 2:45 total', ar_recipe:'١٥ غم لكل ٢٥٠ غم ماء، ٢:٤٥ دقيقة' },
  { id:'chemex',     name:'Chemex / Batch Filter', ar:'كيمكس أو فلتر',
    grind:'Medium-coarse',   ar_grind:'متوسط الخشونة',
    recipe:'60 g per litre, 4 minutes', ar_recipe:'٦٠ غم لكل لتر، ٤ دقائق' },
  { id:'frenchpress',name:'French Press',     ar:'فرنش برس',
    grind:'Coarse',          ar_grind:'خشن',
    recipe:'70 g per litre, steep 4 minutes', ar_recipe:'٧٠ غم لكل لتر، منقوع ٤ دقائق' },
  { id:'moka',       name:'Moka Pot',         ar:'موكا بوت',
    grind:'Fine-medium',     ar_grind:'ناعم إلى متوسط',
    recipe:'Fill the basket level, off the heat early', ar_recipe:'املأ السلة بالتساوي وارفعها مبكراً' },
  { id:'aeropress',  name:'AeroPress',        ar:'إيروبرس',
    grind:'Medium-fine',     ar_grind:'متوسط النعومة',
    recipe:'15 g to 220 g, inverted, 1:30', ar_recipe:'١٥ غم لكل ٢٢٠ غم، مقلوب، ١:٣٠' },
  { id:'coldbrew',   name:'Cold Brew',        ar:'قهوة باردة منقوعة',
    grind:'Extra coarse',    ar_grind:'خشن جداً',
    recipe:'80 g per litre, 16 hours in the fridge', ar_recipe:'٨٠ غم لكل لتر، ١٦ ساعة في الثلاجة' },
];

/* ==================================================== WORLD MAP GEOMETRY
   Coarse equirectangular outlines, stored as [lon, lat] rings and projected
   at draw time. Detailed enough to read as a world map at 900 px wide. */
const LANDMASS = {
  namerica:[[-168,66],[-160,71],[-140,70],[-128,70],[-110,68],[-95,68],[-85,70],[-80,73],[-70,66],[-64,60],
    [-56,52],[-60,46],[-66,44],[-70,42],[-74,39],[-76,35],[-81,31],[-80,25],[-84,30],[-90,29],[-97,28],
    [-97,22],[-92,18],[-88,21],[-87,16],[-83,9],[-79,9],[-83,15],[-95,16],[-105,20],[-110,24],[-114,30],
    [-117,33],[-122,37],[-124,42],[-124,48],[-131,53],[-140,60],[-150,60],[-158,56],[-165,60]],
  samerica:[[-81,0],[-79,-5],[-75,-14],[-70,-18],[-70,-25],[-72,-35],[-73,-45],[-75,-52],[-68,-55],[-65,-55],
    [-62,-40],[-58,-34],[-53,-33],[-48,-25],[-40,-20],[-35,-8],[-35,-5],[-44,-2],[-50,0],[-52,4],[-60,8],
    [-68,11],[-72,12],[-77,8],[-79,2]],
  africa:[[-17,15],[-16,20],[-13,28],[-10,31],[-5,36],[3,37],[10,34],[20,32],[25,32],[32,31],[35,28],[39,22],
    [43,12],[51,12],[48,5],[41,-2],[40,-10],[35,-20],[32,-26],[28,-33],[20,-35],[18,-30],[14,-22],[12,-16],
    [9,-1],[2,4],[-5,5],[-10,4],[-13,9]],
  eurasia:[[-10,36],[0,43],[9,44],[13,38],[18,40],[24,40],[27,36],[36,36],[36,30],[43,30],[48,30],[56,25],
    [62,25],[68,24],[72,20],[77,8],[80,6],[87,21],[92,21],[95,16],[99,10],[104,1],[110,1],[107,10],[109,15],
    [112,22],[120,23],[122,31],[122,38],[126,40],[129,43],[135,45],[142,46],[143,54],[135,55],[140,60],
    [150,60],[160,60],[170,66],[180,66],[180,72],[160,72],[140,73],[120,73],[100,76],[80,73],[70,72],[60,70],
    [50,68],[40,66],[30,68],[28,70],[25,66],[21,64],[21,58],[12,58],[10,63],[5,59],[8,54],[4,52],[-2,50],
    [-2,43],[-8,43]],
  australia:[[113,-22],[114,-27],[116,-32],[122,-34],[129,-32],[135,-35],[138,-35],[141,-38],[146,-39],
    [150,-37],[153,-28],[153,-25],[146,-19],[142,-11],[136,-12],[130,-11],[126,-14],[122,-17],[117,-20]],
  greenland:[[-45,60],[-50,64],[-52,68],[-58,72],[-55,78],[-45,82],[-30,82],[-22,76],[-25,70],[-33,66],[-40,62]],
  sumatra:[[95,5],[99,3],[104,-2],[106,-6],[103,-5],[98,1]],
  java:[[105,-6],[114,-8],[114,-9],[105,-7]],
  sulawesi:[[119,1],[125,1],[124,-5],[120,-5],[120,-2]],
  png:[[131,-2],[141,-3],[150,-6],[147,-9],[141,-9],[134,-8]],
  madagascar:[[44,-16],[50,-15],[50,-25],[45,-25],[43,-20]],
  japan:[[130,32],[136,35],[141,41],[145,44],[141,38],[136,34]],
  nz:[[173,-35],[178,-38],[174,-42],[168,-47],[167,-44],[171,-40]],
  britain:[[-5,50],[1,51],[0,54],[-2,58],[-5,57],[-5,53]],
};

/* ---------------------------------------------------------------- BEANS */
const BEANS = [
  { id:'b-ember', name:'Ember House Blend', ar_name:'خلطة إمبر البيتية',
    origin:'Brazil · Ethiopia', ar_origin:'البرازيل · إثيوبيا', lon:-47, lat:-15,
    roast:'Medium', ar_roast:'تحميص متوسط',
    notes:'Cocoa nib, toasted almond, dried fig', ar_notes:'حبيبات كاكاو، لوز محمّص، تين مجفف',
    price:5.250, tag:'Bestseller', ar_tag:'الأكثر مبيعاً', tagClass:'tag-ember',
    methods:['espresso','moka','aeropress','frenchpress'], c1:'#6b4326', c2:'#3d2314',
    desc:'Our everyday anchor. Built for milk, forgiving on a bad morning, and the bean behind every latte on the bar.',
    ar_desc:'أساسنا اليومي. صُمّمت للحليب، متسامحة في الصباحات الصعبة، وهي الحبة خلف كل لاتيه عندنا.' },

  { id:'b-nitro', name:'Nitro Tap Reserve', ar_name:'احتياطي النيترو',
    origin:'Colombia · Huila', ar_origin:'كولومبيا · هويلا', lon:-75.5, lat:2.5,
    roast:'Medium-Dark', ar_roast:'تحميص متوسط غامق',
    notes:'Dark cocoa, molasses, clean finish', ar_notes:'كاكاو داكن، دبس، نهاية نظيفة',
    price:6.000, tag:'On tap', ar_tag:'على الصنبور', tagClass:'tag-plum',
    methods:['coldbrew','frenchpress','espresso'], c1:'#4b2c19', c2:'#241109',
    desc:'Cold-brewed slow, pushed through nitrogen. Take home the bag we pull the tap from.',
    ar_desc:'تُنقع باردة على مهل ثم تُدفع بالنيتروجين. خذ معك الكيس نفسه الذي نسحب منه.' },

  { id:'b-yirg', name:'Yirgacheffe Kochere', ar_name:'يرغاتشيفي كوتشيري',
    origin:'Ethiopia · Gedeo', ar_origin:'إثيوبيا · غيديو', lon:38.2, lat:6.2,
    roast:'Light', ar_roast:'تحميص فاتح',
    notes:'Bergamot, peach, jasmine', ar_notes:'برغموت، خوخ، ياسمين',
    price:7.250, tag:'Single origin', ar_tag:'أصل واحد', tagClass:'tag-sage',
    methods:['v60','chemex','aeropress'], c1:'#a9763f', c2:'#6d4522',
    desc:'Washed and floral to the point of showing off. Best as filter, unforgettable as an espresso tonic.',
    ar_desc:'مغسولة وزهرية لدرجة التباهي. الأفضل كقهوة مقطّرة، ولا تُنسى مع الماء الفوار.' },

  { id:'b-geisha', name:'Panama Geisha, Lot 04', ar_name:'قيشا بنما، دفعة ٠٤',
    origin:'Panama · Boquete', ar_origin:'بنما · بوكيتي', lon:-82.4, lat:8.8,
    roast:'Light', ar_roast:'تحميص فاتح',
    notes:'Jasmine, white peach, honeysuckle', ar_notes:'ياسمين، خوخ أبيض، زهر العسل',
    price:16.500, tag:'Micro-lot', ar_tag:'دفعة نادرة', tagClass:'tag-gold',
    methods:['v60','chemex'], c1:'#c19a5e', c2:'#8a5f2c',
    desc:'Forty-two bags exist. We got six. Weigh it like it costs what it costs, because it does.',
    ar_desc:'لا يوجد سوى ٤٢ كيساً في العالم، حصلنا على ستة. زِنها بدقة، فسعرها يستحق ذلك.' },

  { id:'b-sumatra', name:'Sumatra Wet-Hulled', ar_name:'سومطرة منزوعة القشرة رطباً',
    origin:'Indonesia · Aceh', ar_origin:'إندونيسيا · آتشيه', lon:97, lat:4.5,
    roast:'Dark', ar_roast:'تحميص غامق',
    notes:'Cedar, baker’s chocolate, tobacco', ar_notes:'أرز، شوكولاتة خام، تبغ',
    price:5.750, tag:'', ar_tag:'', tagClass:'',
    methods:['frenchpress','moka','espresso','coldbrew'], c1:'#3f2717', c2:'#1d0f08',
    desc:'Earthy, syrupy and completely unbothered by oat milk. The one our regulars buy by the kilo.',
    ar_desc:'ترابية وكثيفة ولا يزعجها حليب الشوفان أبداً. زبائننا الدائمون يشترونها بالكيلو.' },

  { id:'b-yemen', name:'Yemeni Mokha Matari', ar_name:'مخا مطري يمني',
    origin:'Yemen · Bani Matar', ar_origin:'اليمن · بني مطر', lon:44, lat:15.3,
    roast:'Medium', ar_roast:'تحميص متوسط',
    notes:'Dried date, cardamom, cocoa, wild spice', ar_notes:'تمر مجفف، هيل، كاكاو، بهار بري',
    price:12.750, tag:'Heritage', ar_tag:'تراثية', tagClass:'tag-gold',
    methods:['turkish','espresso','moka'], c1:'#7a4a28', c2:'#3a1d0d',
    desc:'Terrace-grown at 2,200 m and sun-dried on rooftops. The oldest coffee road there is, and still the most interesting cup in the shop.',
    ar_desc:'تُزرع على مدرجات على ارتفاع ٢٢٠٠ م وتُجفف على الأسطح. أقدم طرق القهوة، وما زالت أكثر فنجان مثير للاهتمام لدينا.' },

  { id:'b-qahwa', name:'Qahwa Blonde, Cardamom-Ready', ar_name:'قهوة عربية شقراء، جاهزة للهيل',
    origin:'Ethiopia · Guji', ar_origin:'إثيوبيا · جوجي', lon:38.8, lat:5.5,
    roast:'Very Light', ar_roast:'تحميص فاتح جداً',
    notes:'Green cardamom, saffron, lemon blossom', ar_notes:'هيل أخضر، زعفران، زهر الليمون',
    price:6.500, tag:'Made for the dallah', ar_tag:'مصنوعة للدلة', tagClass:'tag-sage',
    methods:['turkish'], c1:'#c8a878', c2:'#8f6a3c',
    desc:'Roasted blonde on purpose so the cardamom and saffron have somewhere to sit. This is the bag to keep next to the dallah.',
    ar_desc:'محمّصة فاتحة عن قصد ليجد الهيل والزعفران مكانهما. هذا هو الكيس الذي يوضع بجانب الدلة.' },

  { id:'b-costa', name:'Costa Rica Anaerobic Strawberry', ar_name:'كوستاريكا فراولة لاهوائية',
    origin:'Costa Rica · Tarrazú', ar_origin:'كوستاريكا · تاراسو', lon:-84, lat:9.6,
    roast:'Light', ar_roast:'تحميص فاتح',
    notes:'Strawberry jam, rose, sparkling acidity', ar_notes:'مربى فراولة، ورد، حموضة منعشة',
    price:9.500, tag:'Experimental', ar_tag:'تجريبية', tagClass:'tag-ember',
    methods:['v60','aeropress','chemex'], c1:'#b0503f', c2:'#6d2a20',
    desc:'96 hours sealed in a tank. Tastes so much like strawberry that people accuse us of cheating.',
    ar_desc:'٩٦ ساعة محكمة الإغلاق في خزان. طعمها فراولة لدرجة أن الناس يتهموننا بالغش.' },

  { id:'b-espresso', name:'Bakehouse Espresso', ar_name:'إسبريسو المخبز',
    origin:'Guatemala · Peru', ar_origin:'غواتيمالا · بيرو', lon:-90.5, lat:14.6,
    roast:'Medium-Dark', ar_roast:'تحميص متوسط غامق',
    notes:'Caramel, walnut, baked apple', ar_notes:'كراميل، جوز، تفاح مخبوز',
    price:5.500, tag:'', ar_tag:'', tagClass:'',
    methods:['espresso','moka'], c1:'#5a3520', c2:'#2b1610',
    desc:'Roasted for the pastry case: sweet enough to stand next to a croissant without arguing.',
    ar_desc:'محمّصة لتناسب المعجنات: حلوة بما يكفي لتقف بجانب الكرواسون دون خلاف.' },

  { id:'b-kenya', name:'Kenya Nyeri AA', ar_name:'كينيا نيري AA',
    origin:'Kenya · Nyeri', ar_origin:'كينيا · نيري', lon:36.95, lat:-0.42,
    roast:'Light-Medium', ar_roast:'تحميص فاتح إلى متوسط',
    notes:'Blackcurrant, tomato leaf, grapefruit', ar_notes:'كشمش أسود، ورق طماطم، جريب فروت',
    price:8.250, tag:'', ar_tag:'', tagClass:'',
    methods:['v60','chemex','aeropress','coldbrew'], c1:'#8d5230', c2:'#4d2412',
    desc:'The loudest coffee we sell. Savoury, tart, and completely unmistakable in a blind cup.',
    ar_desc:'أعلى قهوة صوتاً لدينا. مالحة، حامضة، ولا يمكن الخلط بينها وبين غيرها في التذوق الأعمى.' },

  { id:'b-decaf', name:'Midnight Decaf', ar_name:'ديكاف منتصف الليل',
    origin:'Colombia · Sugarcane EA', ar_origin:'كولومبيا · بقصب السكر', lon:-74, lat:5,
    roast:'Medium', ar_roast:'تحميص متوسط',
    notes:'Milk chocolate, cherry, brown sugar', ar_notes:'شوكولاتة بالحليب، كرز، سكر بني',
    price:5.750, tag:'Decaf', ar_tag:'خالية من الكافيين', tagClass:'',
    methods:['espresso','v60','frenchpress','moka','aeropress'], c1:'#5d3a23', c2:'#2f1a0e',
    desc:'Decaffeinated with sugarcane ethyl acetate, so it still tastes like coffee at 9pm.',
    ar_desc:'منزوعة الكافيين بطريقة قصب السكر، فتبقى بطعم القهوة الحقيقي في التاسعة مساءً.' },

  { id:'b-png', name:'Papua New Guinea Sigri', ar_name:'بابوا غينيا الجديدة سيغري',
    origin:'PNG · Waghi Valley', ar_origin:'بابوا غينيا · وادي واغي', lon:144.5, lat:-5.8,
    roast:'Medium', ar_roast:'تحميص متوسط',
    notes:'Brown sugar, orange peel, cedar', ar_notes:'سكر بني، قشر برتقال، أرز',
    price:6.750, tag:'', ar_tag:'', tagClass:'',
    methods:['chemex','frenchpress','moka','v60'], c1:'#7b4b28', c2:'#3c2010',
    desc:'Grown on smallholder plots at 1,600 m. Balanced enough to be the bag you never have to think about.',
    ar_desc:'تُزرع في حيازات صغيرة على ارتفاع ١٦٠٠ م. متوازنة لدرجة أنك لن تفكر فيها كثيراً.' },
];

/* ------------------------------------------------------------- SUPPLIES
   cat: flour | chocolate | matcha | pantry | tools | syrup | cream        */
const SUPPLIES = [
  { id:'s-t55', name:'T55 French Bread Flour', ar_name:'دقيق خبز فرنسي T55', cat:'flour', unit:'2 kg', ar_unit:'٢ كغم', price:3.750,
    notes:'11.5% protein · stone-milled', ar_notes:'بروتين ١١.٥٪ · مطحون بالحجر', c1:'#efe3cd', c2:'#dbc9ab',
    desc:'The flour our laminated dough is built on. Slack, extensible, and beautifully thirsty.',
    ar_desc:'الدقيق الذي تُبنى عليه عجينتنا المورّقة. طري، قابل للمد، وعطش بشكل جميل.' },
  { id:'s-t65', name:'T65 Viennoiserie Flour', ar_name:'دقيق معجنات T65', cat:'flour', unit:'2 kg', ar_unit:'٢ كغم', price:4.250,
    notes:'Higher ash · croissant-grade', ar_notes:'رماد أعلى · درجة الكرواسون', c1:'#eddfc5', c2:'#d5c09e',
    desc:'For anyone who has decided this is the winter they finally learn lamination.',
    ar_desc:'لمن قرر أن هذا هو الشتاء الذي سيتعلم فيه التوريق أخيراً.' },
  { id:'s-choc', name:'Valrhona Guanaja 70%', ar_name:'فالرونا غواناخا ٧٠٪', cat:'chocolate', unit:'1 kg', ar_unit:'١ كغم', price:11.500,
    notes:'Bitter, long, faintly floral', ar_notes:'مرّة، طويلة، زهرية خفيفة', c1:'#4a2c1c', c2:'#23120b',
    desc:'The ganache standard. If a recipe just says "dark chocolate," it quietly means this.',
    ar_desc:'معيار الغاناش. إن قالت الوصفة «شوكولاتة داكنة» فهي تعني هذه بالتحديد.' },
  { id:'s-dulcey', name:'Dulcey Blond 32%', ar_name:'دولسي بلوند ٣٢٪', cat:'chocolate', unit:'1 kg', ar_unit:'١ كغم', price:10.750,
    notes:'Shortbread, toasted milk', ar_notes:'بسكويت زبدة، حليب محمّص', c1:'#d0a463', c2:'#a97b3c',
    desc:'Caramelised white chocolate. Dangerous to keep within arm’s reach of the workbench.',
    ar_desc:'شوكولاتة بيضاء مكرملة. من الخطر إبقاؤها قريبة من طاولة العمل.' },
  { id:'s-cocoa', name:'Dutch-Process Cocoa', ar_name:'كاكاو هولندي المعالجة', cat:'chocolate', unit:'750 g', ar_unit:'٧٥٠ غم', price:5.250,
    notes:'22–24% fat · deep red', ar_notes:'دهون ٢٢–٢٤٪ · أحمر عميق', c1:'#6a3b23', c2:'#37190e',
    desc:'The dusting on every tiramisù that leaves this building.',
    ar_desc:'الرشّة التي تعلو كل تيراميسو يخرج من هنا.' },
  { id:'s-matcha', name:'Ceremonial Matcha, Uji', ar_name:'ماتشا احتفالية، أوجي', cat:'matcha', unit:'100 g tin', ar_unit:'علبة ١٠٠ غم', price:12.750,
    notes:'First harvest · stone-ground', ar_notes:'أول حصاد · مطحونة بالحجر', c1:'#7fa05a', c2:'#4d6b32',
    desc:'Vivid, low-astringency, and the exact tin behind every matcha on our menu.',
    ar_desc:'زاهية وقليلة القبض، وهي العلبة نفسها خلف كل ماتشا في قائمتنا.' },
  { id:'s-culinary', name:'Culinary Matcha, Kirishima', ar_name:'ماتشا للطهي، كيريشيما', cat:'matcha', unit:'250 g', ar_unit:'٢٥٠ غم', price:8.500,
    notes:'For sponges, creams and glazes', ar_notes:'للكيك والكريمات والتزجيج', c1:'#8fa864', c2:'#5c7738',
    desc:'Bolder and built to survive being baked, whipped, or folded into mascarpone.',
    ar_desc:'أقوى ومصمّمة لتتحمل الخبز والخفق والدمج مع الماسكاربوني.' },
  { id:'s-vanilla', name:'Madagascar Vanilla Beans', ar_name:'أعواد فانيلا مدغشقرية', cat:'pantry', unit:'10 pods', ar_unit:'١٠ أعواد', price:7.750,
    notes:'Grade A · Bourbon', ar_notes:'درجة أولى · بوربون', c1:'#503726', c2:'#291a11',
    desc:'Plump, oily and split-ready. Please do not use these in a candle.',
    ar_desc:'ممتلئة وزيتية وجاهزة للشق. أرجوك لا تستخدمها في شمعة.' },
  { id:'s-pistachio', name:'Sicilian Pistachio Paste', ar_name:'معجون فستق صقلي', cat:'pantry', unit:'500 g', ar_unit:'٥٠٠ غم', price:13.250,
    notes:'100% Bronte · no sugar added', ar_notes:'برونتي ١٠٠٪ · بدون سكر مضاف', c1:'#93a760', c2:'#5f7136',
    desc:'One ingredient. Green the way a real pistachio is green, not the way a syrup is.',
    ar_desc:'مكوّن واحد. أخضر كما الفستق الحقيقي، لا كما الشراب الصناعي.' },
  { id:'s-straw', name:'Freeze-Dried Strawberry Powder', ar_name:'بودرة فراولة مجففة بالتجميد', cat:'pantry', unit:'200 g', ar_unit:'٢٠٠ غم', price:5.750,
    notes:'Pure fruit · nothing else', ar_notes:'فاكهة خالصة · لا شيء آخر', c1:'#d4634f', c2:'#9c3527',
    desc:'The secret in our strawberry matcha lady fingers. Intense, tart, and shockingly pink.',
    ar_desc:'سر أصابع السيدة بالفراولة والماتشا عندنا. مركّزة وحامضة ووردية بشكل صادم.' },
  { id:'s-cardamom', name:'Green Cardamom, Hand-Sorted', ar_name:'هيل أخضر مفروز يدوياً', cat:'pantry', unit:'250 g', ar_unit:'٢٥٠ غم', price:6.250,
    notes:'Whole pods · for the dallah', ar_notes:'حبات كاملة · للدلة', c1:'#a8b47c', c2:'#6d7a44',
    desc:'Sorted by hand so every pod is plump and green. Crack them the minute before, never before that.',
    ar_desc:'مفروز يدوياً لتكون كل حبة ممتلئة وخضراء. اكسرها قبل الاستعمال بدقيقة، لا قبل ذلك.' },
  { id:'s-culture', name:'Live Sourdough Culture', ar_name:'خميرة عجين مخمّر حية', cat:'pantry', unit:'Since day one', ar_unit:'منذ اليوم الأول', price:3.250,
    notes:'Vigorous · rye-fed', ar_notes:'نشطة · تُغذّى بالجاودار', c1:'#e2d0ae', c2:'#bfa77e',
    desc:'A spoonful of the starter we have kept alive since our first week. Feed it. Name it.',
    ar_desc:'ملعقة من الخميرة التي أبقيناها حية منذ أسبوعنا الأول. أطعمها، وسمّها.' },
  { id:'s-scale', name:'Bakehouse Precision Scale', ar_name:'ميزان المخبز الدقيق', cat:'tools', unit:'0.1 g · 5 kg', ar_unit:'٠.١ غم · ٥ كغم', price:17.500,
    notes:'Pastry-grade accuracy', ar_notes:'دقة احترافية للحلويات', c1:'#b9b3aa', c2:'#7d766c',
    desc:'Reads to a tenth of a gram, which is the difference between ganache and a sad puddle.',
    ar_desc:'يقرأ حتى عُشر الغرام، وهو الفرق بين غاناش ناجح وبركة حزينة.' },
  { id:'s-rings', name:'Perforated Tart Rings, Set of 4', ar_name:'حلقات تارت مثقبة، طقم ٤', cat:'tools', unit:'70–200 mm', ar_unit:'٧٠–٢٠٠ مم', price:14.250,
    notes:'Micro-perforated steel', ar_notes:'فولاذ دقيق التثقيب', c1:'#c3bcb2', c2:'#878076',
    desc:'Even browning, straight walls, and no more soggy bottoms to apologise for.',
    ar_desc:'تحمير متساوٍ وجدران مستقيمة، ولا مزيد من القيعان الطرية المحرجة.' },
  { id:'s-bench', name:'Maple Bench Scraper', ar_name:'كاشطة عجين من خشب القيقب', cat:'tools', unit:'Hand-turned', ar_unit:'مصنوعة يدوياً', price:6.500,
    notes:'Turned by hand', ar_notes:'مخروطة يدوياً', c1:'#d3ab73', c2:'#a67a44',
    desc:'Turned by a woodworker two streets over in Zahra. It will outlive the oven.',
    ar_desc:'خرطها نجّار على بعد شارعين. ستعمّر أطول من الفرن.' },

  /* ---- house syrups, bottled ---- */
  { id:'y-cinn', name:'Cinnamon Sugar Syrup', ar_name:'شراب القرفة والسكر', cat:'syrup', unit:'375 ml', ar_unit:'٣٧٥ مل', price:2.750,
    notes:'Ceylon cinnamon · demerara', ar_notes:'قرفة سيلانية · سكر ديميرارا', c1:'#c08c4f', c2:'#8a5c30',
    desc:'The syrup behind our most-ordered latte. Two pumps in milk, one over porridge.',
    ar_desc:'الشراب خلف أكثر لاتيه يُطلب عندنا. ضخّتان في الحليب، وواحدة على الشوفان.' },
  { id:'y-banana', name:'Caramelised Banana Syrup', ar_name:'شراب الموز المكرمل', cat:'syrup', unit:'375 ml', ar_unit:'٣٧٥ مل', price:2.950,
    notes:'Roasted banana · brown sugar', ar_notes:'موز محمّص · سكر بني', c1:'#d9b160', c2:'#96632c',
    desc:'Bananas roasted until they taste like the inside of a banana bread, then strained.',
    ar_desc:'موز محمّص حتى يصبح طعمه كقلب كيك الموز، ثم يُصفّى.' },
  { id:'y-rose', name:'Rose Cardamom Syrup', ar_name:'شراب الورد والهيل', cat:'syrup', unit:'375 ml', ar_unit:'٣٧٥ مل', price:3.250,
    notes:'Taif rose · green cardamom', ar_notes:'ورد طائفي · هيل أخضر', c1:'#d59aa6', c2:'#a2687a',
    desc:'Built for the Gulf palate: floral, warm, and very good over cold milk and ice.',
    ar_desc:'مصنوع للذوق الخليجي: زهري ودافئ، ولذيذ جداً على الحليب البارد والثلج.' },
  { id:'y-date', name:'Salted Date Syrup', ar_name:'شراب التمر المملّح', cat:'syrup', unit:'375 ml', ar_unit:'٣٧٥ مل', price:2.950,
    notes:'Khalas dates · sea salt', ar_notes:'تمر خلاص · ملح بحري', c1:'#96603a', c2:'#5e3a1f',
    desc:'Khalas dates cooked down with a pinch of salt. Tastes like the Gulf, works like caramel.',
    ar_desc:'تمر خلاص مطبوخ مع رشة ملح. طعمه خليجي، ويعمل كالكراميل.' },
  { id:'y-ginger', name:'Ginger Citrus Syrup', ar_name:'شراب الزنجبيل والحمضيات', cat:'syrup', unit:'375 ml', ar_unit:'٣٧٥ مل', price:2.750,
    notes:'Fresh ginger · orange peel', ar_notes:'زنجبيل طازج · قشر برتقال', c1:'#dda85c', c2:'#9a6021',
    desc:'Sharp, warming and the only thing that makes tonic water interesting.',
    ar_desc:'حاد ومدفئ، وهو الشيء الوحيد الذي يجعل الماء الفوار مثيراً.' },
  { id:'y-lavender', name:'Lavender Honey Syrup', ar_name:'شراب الخزامى بالعسل', cat:'syrup', unit:'375 ml', ar_unit:'٣٧٥ مل', price:3.250,
    notes:'Culinary lavender · wildflower honey', ar_notes:'خزامى للطهي · عسل زهور برية', c1:'#b3a1c6', c2:'#7b6a8f',
    desc:'Restrained on purpose. It should taste like a garden, not like soap.',
    ar_desc:'مضبوط عن قصد. يجب أن يكون طعمه كحديقة، لا كصابون.' },
  { id:'y-set', name:'Syrup Flight, Any Four', ar_name:'رحلة الشرابات، أربعة بالاختيار', cat:'syrup', unit:'4 × 200 ml', ar_unit:'٤ × ٢٠٠ مل', price:8.500,
    notes:'Pick four · gift-boxed', ar_notes:'اختر أربعة · بعلبة هدية', c1:'#cf9d6b', c2:'#8a5c30',
    desc:'Four small bottles in a box, chosen at the counter. The present we sell most of in Ramadan.',
    ar_desc:'أربع قوارير صغيرة في علبة، تُختار عند الكاونتر. أكثر هدية نبيعها في رمضان.' },

  /* ---- cake creams & fillings, tubbed ---- */
  { id:'k-masc', name:'Mascarpone Cream, Whipped', ar_name:'كريمة ماسكاربوني مخفوقة', cat:'cream', unit:'500 g', ar_unit:'٥٠٠ غم', price:4.250,
    notes:'Ready to layer · 5 day life', ar_notes:'جاهزة للطبقات · تدوم ٥ أيام', c1:'#f7edd8', c2:'#d8c8a6',
    desc:'The exact cream we put between tiramisù layers, in a tub, so you can stop making it at midnight.',
    ar_desc:'الكريمة نفسها التي نضعها بين طبقات التيراميسو، في علبة، لتتوقف عن صنعها منتصف الليل.' },
  { id:'k-matcha', name:'Matcha Cream', ar_name:'كريمة الماتشا', cat:'cream', unit:'500 g', ar_unit:'٥٠٠ غم', price:5.500,
    notes:'Uji culinary grade', ar_notes:'ماتشا أوجي للطهي', c1:'#b9cf8e', c2:'#89a05c',
    desc:'Whipped with white chocolate so it holds its shape and its colour for three days.',
    ar_desc:'مخفوقة مع الشوكولاتة البيضاء لتحافظ على شكلها ولونها ثلاثة أيام.' },
  { id:'k-ganache', name:'Guanaja Ganache', ar_name:'غاناش غواناخا', cat:'cream', unit:'500 g', ar_unit:'٥٠٠ غم', price:5.750,
    notes:'70% · pipe cold, drip warm', ar_notes:'٧٠٪ · تُشكّل باردة وتُسكب دافئة', c1:'#3f2415', c2:'#1c0e07',
    desc:'Warm it for a drip, chill it and whip it for a filling. Two desserts from one tub.',
    ar_desc:'سخّنها للتقطير، أو برّدها واخفقها للحشو. حلويان من علبة واحدة.' },
  { id:'k-pist', name:'Pistachio Cream', ar_name:'كريمة الفستق', cat:'cream', unit:'400 g', ar_unit:'٤٠٠ غم', price:7.250,
    notes:'Bronte paste · low sugar', ar_notes:'معجون برونتي · سكر قليل', c1:'#bcca85', c2:'#8b9a52',
    desc:'Enough Bronte paste in it that the colour is real. Spoonable straight from the tub, allegedly.',
    ar_desc:'فيها من معجون برونتي ما يجعل اللون حقيقياً. تُؤكل بالملعقة مباشرة، حسب الشائعات.' },
  { id:'k-caramel', name:'Salted Date Caramel', ar_name:'كراميل التمر المملّح', cat:'cream', unit:'400 g', ar_unit:'٤٠٠ غم', price:4.750,
    notes:'Khalas dates · flaky salt', ar_notes:'تمر خلاص · ملح رقائقي', c1:'#b57736', c2:'#7a4a1c',
    desc:'Our date syrup cooked further with cream until it behaves like a proper caramel.',
    ar_desc:'شراب التمر عندنا مطبوخ أكثر مع الكريمة حتى يتصرف ككراميل حقيقي.' },
  { id:'k-royal', name:'Royal Icing Kit, 6 Colours', ar_name:'طقم آيسنغ ملكي، ٦ ألوان', cat:'cream', unit:'6 × 150 g', ar_unit:'٦ × ١٥٠ غم', price:6.750,
    notes:'Piping consistency · tips included', ar_notes:'قوام مناسب للتشكيل · مع رؤوس', c1:'#fbf4e6', c2:'#dccdb1',
    desc:'Six squeeze bottles in the same colours the Cookie Studio uses, so a cookie you designed here can be made at home.',
    ar_desc:'ست قوارير بنفس ألوان استوديو الكوكيز، لتصنع في بيتك ما صمّمته عندنا.' },
];

/* ---------------------------------------------------------- DRINK MENU */
const DRINKS = [
  { id:'d-nitro', name:'Nitro Cold Brew', ar_name:'نيترو كولد برو', cat:'nitro', price:1.600, c1:'#3a2114', c2:'#150a05',
    tag:'House icon', ar_tag:'أيقونة المحل', tagClass:'tag-plum',
    desc:'Sixteen-hour cold brew poured through the nitrogen tap. Cascades like a stout, finishes clean, needs nothing.',
    ar_desc:'قهوة باردة منقوعة ١٦ ساعة تُسكب عبر صنبور النيتروجين. تتدرّج كالستاوت، ونهايتها نظيفة، ولا تحتاج شيئاً.' },
  { id:'d-nitrosweet', name:'Sweet Cream Nitro', ar_name:'نيترو بالكريمة الحلوة', cat:'nitro', price:1.850, c1:'#6b452a', c2:'#c7a882',
    desc:'The same tap pour, crowned with vanilla-bean sweet cream that sinks in slow ribbons.',
    ar_desc:'نفس السكب، متوّجاً بكريمة الفانيلا الحلوة التي تنزل بخيوط بطيئة.' },
  { id:'d-espresso', name:'Espresso', ar_name:'إسبريسو', cat:'espresso', price:0.900, c1:'#43240f', c2:'#1c0d05',
    desc:'Bakehouse Espresso, pulled short. Caramel, walnut, and a crema you could stand a spoon in.',
    ar_desc:'إسبريسو المخبز، مسحوب قصيراً. كراميل وجوز وكريما تقف فيها الملعقة.' },
  { id:'d-cortado', name:'Cortado', ar_name:'كورتادو', cat:'espresso', price:1.100, c1:'#8a5a35', c2:'#4d2c16',
    desc:'Two ounces of milk, two ounces of espresso, zero ceremony.',
    ar_desc:'أونصتان حليب، أونصتان إسبريسو، بلا مراسم.' },
  { id:'d-flat', name:'Flat White', ar_name:'فلات وايت', cat:'espresso', price:1.400, c1:'#a5744a', c2:'#5d3a20',
    desc:'Steamed to 60°C with a microfoam thin enough to read a newspaper through.',
    ar_desc:'حليب مبخّر إلى ٦٠° برغوة دقيقة تكاد تقرأ الجريدة من خلالها.' },
  { id:'d-tonic', name:'Espresso Tonic', ar_name:'إسبريسو تونك', cat:'espresso', price:1.750, c1:'#d9c48f', c2:'#7a4a22',
    tag:'Adventurous', ar_tag:'للمغامرين', tagClass:'tag-sage',
    desc:'Yirgacheffe over tonic and a wide strip of grapefruit peel. Bitter, bright, and weirdly refreshing.',
    ar_desc:'يرغاتشيفي على ماء فوار مع شريحة عريضة من قشر الجريب فروت. مرّة ومشرقة ومنعشة بشكل غريب.' },
  { id:'d-cinn', name:'Cinnamon Sugar Latte', ar_name:'لاتيه القرفة والسكر', cat:'signature', price:1.900, c1:'#c69a68', c2:'#8a5c30',
    tag:'Bestseller', ar_tag:'الأكثر مبيعاً', tagClass:'tag-ember',
    desc:'House cinnamon-sugar syrup, whole milk, and a churro-style dusting across the foam.',
    ar_desc:'شراب القرفة والسكر البيتي مع الحليب كامل الدسم ورشة تشورو على الرغوة.' },
  { id:'d-banana', name:'Caramelised Banana Latte', ar_name:'لاتيه الموز المكرمل', cat:'signature', price:2.100, c1:'#d8b46f', c2:'#96632c',
    desc:'Bananas roasted dark with brown sugar until they taste like the inside of a banana bread.',
    ar_desc:'موز محمّص بالسكر البني حتى يصبح طعمه كقلب كيك الموز.' },
  { id:'d-rcc', name:'Raspberry Chocolate Chip', ar_name:'توت أحمر بقطع الشوكولاتة', cat:'signature', price:2.100, c1:'#b8607a', c2:'#5e2b3a',
    tag:'Ice-cream inspired', ar_tag:'مستوحى من الآيس كريم', tagClass:'tag-plum',
    desc:'Raspberry syrup, drinking chocolate, and a shower of chocolate shards that get stuck in the straw. Worth it.',
    ar_desc:'شراب التوت مع الشوكولاتة السائلة ورشّة من شظايا الشوكولاتة التي تعلق بالشفاطة. تستحق ذلك.' },
  { id:'d-strawmatcha', name:'Strawberry Matcha Cloud', ar_name:'سحابة الفراولة والماتشا', cat:'signature', price:2.250, c1:'#e08a94', c2:'#6f8f4e',
    tag:'Most photographed', ar_tag:'الأكثر تصويراً', tagClass:'tag-ember',
    desc:'Freeze-dried strawberry milk poured under ceremonial matcha, finished with strawberry cold foam.',
    ar_desc:'حليب الفراولة المجففة يُسكب تحت الماتشا الاحتفالية، ويُختم برغوة الفراولة الباردة.' },
  { id:'d-ginger', name:'Ginger Citrus Latte', ar_name:'لاتيه الزنجبيل والحمضيات', cat:'signature', price:2.000, c1:'#dda85c', c2:'#9a6021',
    desc:'Fresh ginger simmered with orange and lemon peel. The one people order all winter.',
    ar_desc:'زنجبيل طازج مطهو مع قشر البرتقال والليمون. المشروب الذي يُطلب طوال الشتاء.' },
  { id:'d-rosecard', name:'Rose Cardamom Latte', ar_name:'لاتيه الورد والهيل', cat:'signature', price:2.100, c1:'#dda8b4', c2:'#8f6072',
    tag:'Gulf favourite', ar_tag:'المفضّل خليجياً', tagClass:'tag-gold',
    desc:'Taif rose and green cardamom in whole milk. Tastes like a majlis at the end of a long evening.',
    ar_desc:'ورد طائفي وهيل أخضر في حليب كامل الدسم. طعمه كمجلس في آخر سهرة طويلة.' },
  { id:'d-datelatte', name:'Salted Date Latte', ar_name:'لاتيه التمر المملّح', cat:'signature', price:2.000, c1:'#c08f5c', c2:'#6b3f1c',
    desc:'Khalas date syrup, a pinch of sea salt, and enough espresso to keep it from being dessert.',
    ar_desc:'شراب تمر الخلاص ورشة ملح بحري وإسبريسو يكفي لئلا يصبح حلوى.' },
  { id:'d-lav', name:'Lavender Honey Latte', ar_name:'لاتيه الخزامى بالعسل', cat:'signature', price:2.000, c1:'#b9a6c4', c2:'#6f5c7c',
    desc:'Culinary lavender steeped in local wildflower honey. Restrained — it should not taste like soap.',
    ar_desc:'خزامى منقوعة في عسل الزهور البرية. مضبوطة — يجب ألا يكون طعمها كالصابون.' },
  { id:'d-blue', name:'Blueberry Matcha', ar_name:'ماتشا التوت الأزرق', cat:'matcha', price:2.100, c1:'#8e7fb5', c2:'#5b7a44',
    desc:'Wild blueberry compote at the bottom, Uji matcha on top, oat milk between them.',
    ar_desc:'كومبوت التوت البري في القاع، وماتشا أوجي في الأعلى، وحليب الشوفان بينهما.' },
  { id:'d-matcha', name:'Ceremonial Matcha Latte', ar_name:'لاتيه الماتشا الاحتفالية', cat:'matcha', price:1.950, c1:'#9dbb72', c2:'#5c7c3a',
    desc:'Whisked to order in a chawan, no sweetener unless you ask. Grassy, sweet, faintly oceanic.',
    ar_desc:'تُخفق عند الطلب في وعاء تشاوان، بلا محلّي إلا إن طلبت. عشبية وحلوة وبلمسة بحرية خفيفة.' },
  { id:'d-hoji', name:'Hojicha Oat Latte', ar_name:'لاتيه الهوجيتشا بالشوفان', cat:'matcha', price:1.850, c1:'#b58b5f', c2:'#6d452a',
    desc:'Roasted green tea, naturally low in caffeine, tastes like toasted rice and campfire.',
    ar_desc:'شاي أخضر محمّص، قليل الكافيين طبيعياً، بطعم الأرز المحمّص والنار الهادئة.' },
  { id:'d-qahwa', name:'Arabic Qahwa, Cardamom & Saffron', ar_name:'قهوة عربية بالهيل والزعفران', cat:'other', price:1.500, c1:'#d9bd86', c2:'#a07c3f',
    tag:'Served in a dallah', ar_tag:'تُقدّم في دلة', tagClass:'tag-gold',
    desc:'Our blonde roast, cracked cardamom and a thread of saffron, brought up three times. Comes with two dates.',
    ar_desc:'تحميصتنا الشقراء مع هيل مكسور وخيط زعفران، تُرفع ثلاث مرات. تأتي مع تمرتين.' },
  { id:'d-chai', name:'Cherry Vanilla Chai', ar_name:'شاي كرز وفانيلا', cat:'other', price:1.850, c1:'#c07d64', c2:'#6d3524',
    tag:'No coffee', ar_tag:'بدون قهوة', tagClass:'tag-sage',
    desc:'House masala chai cut with sour cherry and vanilla bean. Order it dirty for a shot on top.',
    ar_desc:'شاي ماسالا بيتي مع الكرز الحامض وعود الفانيلا. اطلبه «دِرتي» لتضاف جرعة إسبريسو.' },
  { id:'d-wafer', name:'The Dirty Wafer', ar_name:'ذا دِرتي ويفر', cat:'other', price:2.150, c1:'#a9743f', c2:'#4c2a14',
    tag:'Cult favourite', ar_tag:'مفضّل الجمهور', tagClass:'tag-gold',
    desc:'Drinking chocolate, hazelnut, a double shot, and a crushed wafer rim. Dessert that thinks it is a drink.',
    ar_desc:'شوكولاتة سائلة وبندق وجرعة مزدوجة وحافة من الويفر المسحوق. حلوى تظن نفسها مشروباً.' },
  { id:'d-choc', name:'Drinking Chocolate', ar_name:'شوكولاتة ساخنة', cat:'other', price:1.650, c1:'#6b3d24', c2:'#301709',
    desc:'Guanaja 70% melted into whole milk. Thick enough that the spoon hesitates.',
    ar_desc:'غواناخا ٧٠٪ مذابة في حليب كامل الدسم. كثيفة لدرجة تتردد فيها الملعقة.' },
];

/* ----------------------------------------------------------- BAKE MENU */
const BAKES = [
  { id:'p-croissant', name:'Butter Croissant', ar_name:'كرواسون بالزبدة', cat:'pastry', price:1.100, c1:'#e0b273', c2:'#a9762f',
    desc:'Seventy-two hours, three folds, one very serious lamination. Shatters when you look at it.',
    ar_desc:'٧٢ ساعة، وثلاث طيّات، وتوريق جادّ جداً. يتفتّت بمجرد النظر إليه.' },
  { id:'p-pain', name:'Pain au Chocolat', ar_name:'بان أو شوكولا', cat:'pastry', price:1.250, c1:'#c99657', c2:'#5b3418',
    desc:'Two batons of Guanaja 70% inside the same dough. Best within nine minutes of the oven.',
    ar_desc:'قطعتان من غواناخا ٧٠٪ داخل العجينة نفسها. الأفضل خلال تسع دقائق من الفرن.' },
  { id:'p-morning', name:'Morning Bun', ar_name:'كعكة الصباح', cat:'pastry', price:1.200, c1:'#e2ae6b', c2:'#9d6428',
    tag:'Sells out', ar_tag:'ينفد بسرعة', tagClass:'tag-ember',
    desc:'Croissant dough rolled in orange zest and cinnamon sugar, baked until the edges caramelise.',
    ar_desc:'عجينة كرواسون ملفوفة ببشر البرتقال والقرفة والسكر، تُخبز حتى تتكرمل الأطراف.' },
  { id:'p-kouign', name:'Kouign-Amann', ar_name:'كوين آمان', cat:'pastry', price:1.350, c1:'#d9a256', c2:'#8c5518',
    desc:'Butter, sugar, and heat behaving badly. Crisp on the outside, molten in the middle.',
    ar_desc:'زبدة وسكر وحرارة تتصرف بشقاوة. مقرمشة من الخارج وذائبة من الداخل.' },
  { id:'p-pistachio', name:'Pistachio Escargot', ar_name:'حلزون الفستق', cat:'pastry', price:1.600, c1:'#c3c07a', c2:'#7b8a3f',
    desc:'Spiralled with Bronte pistachio paste and topped with chopped nuts and a bruléed edge.',
    ar_desc:'ملفوف بمعجون فستق برونتي ومزيّن بالمكسرات المفرومة وحافة مكرملة.' },
  { id:'p-scone', name:'Strawberry Cream Scone', ar_name:'سكون الفراولة بالقشطة', cat:'pastry', price:1.100, c1:'#e8c4b4', c2:'#b4705c',
    desc:'Freeze-dried strawberry folded through the crumb so it never goes soggy.',
    ar_desc:'فراولة مجففة بالتجميد مدمجة في العجين فلا تصبح طرية أبداً.' },
  { id:'p-date', name:'Date & Tahini Bun', ar_name:'كعكة التمر والطحينة', cat:'pastry', price:1.250, c1:'#c99a63', c2:'#6f4522',
    tag:'Local', ar_tag:'محلي', tagClass:'tag-sage',
    desc:'Khalas date paste and sesame tahini swirled through an enriched dough. The one we cannot bake enough of.',
    ar_desc:'معجون تمر خلاص وطحينة سمسم ملفوفان في عجينة غنية. لا نستطيع خبز ما يكفي منها.' },

  { id:'k-brownbutter', name:'Brown Butter Chocolate Chunk', ar_name:'كوكيز الزبدة البنية بقطع الشوكولاتة', cat:'cookie', price:0.950, c1:'#c08a4e', c2:'#5c3417',
    desc:'Rested 36 hours, finished with flaky salt. The cookie we judge other cookies against.',
    ar_desc:'مرتاحة ٣٦ ساعة، ومختومة بملح رقائقي. الكوكيز التي نقيس عليها بقية الكوكيز.' },
  { id:'k-datecard', name:'Date & Cardamom Cookie', ar_name:'كوكيز التمر والهيل', cat:'cookie', price:0.950, c1:'#cda06a', c2:'#6d4322',
    tag:'Local', ar_tag:'محلي', tagClass:'tag-sage',
    desc:'Chewy, spiced, and full of chopped Khalas dates. Somehow better on the second day.',
    ar_desc:'طرية ومبهّرة ومليئة بتمر الخلاص المفروم. وتصبح ألذ في اليوم الثاني بطريقة ما.' },
  { id:'k-rose', name:'Rose Pistachio Shortbread', ar_name:'شورت بريد الورد والفستق', cat:'cookie', price:1.100, c1:'#e0bcc4', c2:'#9a8a5c',
    desc:'Sandy, buttery, dusted with dried rose. Comes in the tin your grandmother will want back.',
    ar_desc:'رملية وزبدية ومرشوشة بالورد المجفف. تأتي في علبة ستطلبها جدتك.' },
  { id:'k-iced', name:'Message Cookie', ar_name:'كوكيز الرسالة', cat:'cookie', price:1.500, c1:'#f6ecd9', c2:'#c9a06a',
    tag:'Studio original', ar_tag:'من الاستوديو', tagClass:'tag-ember',
    desc:'A blank royal-iced plaque with your words piped on in the font you pick. Designed in the Cookie Studio.',
    ar_desc:'لوح آيسنغ ملكي فارغ تُكتب عليه كلماتك بالخط الذي تختاره. يُصمَّم في استوديو الكوكيز.' },
  { id:'k-box12', name:'Cookie Box, Twelve', ar_name:'علبة كوكيز، اثنتا عشرة', cat:'cookie', price:15.500, c1:'#f0dfc4', c2:'#b8794b',
    desc:'A dozen decorated cookies in a ribboned box. The Eid and graduation standby.',
    ar_desc:'اثنتا عشرة كوكيز مزيّنة في علبة بشريطة. الخيار المعتاد للعيد والتخرج.' },

  { id:'c-tiramisu', name:'Classic Tiramisù', ar_name:'تيراميسو كلاسيكي', cat:'cake', price:2.250, whole:16.500, c1:'#e6d5b8', c2:'#5b3a22',
    tag:'By the slice or whole', ar_tag:'بالقطعة أو كاملة', tagClass:'',
    desc:'Savoiardi soaked in Bakehouse Espresso, mascarpone cream, a hard dusting of Dutch cocoa.',
    ar_desc:'أصابع سيدة منقوعة بإسبريسو المخبز، وكريمة ماسكاربوني، ورشّة كثيفة من الكاكاو الهولندي.' },
  { id:'c-strawmatcha', name:'Strawberry Matcha Tiramisù', ar_name:'تيراميسو الفراولة والماتشا', cat:'cake', price:2.500, whole:18.500, c1:'#e5a3ac', c2:'#7ba055',
    tag:'Studio original', ar_tag:'من الاستوديو', tagClass:'tag-ember',
    desc:'A guest designed this in the Cake Studio and we put it on the menu: strawberry-powder-soaked lady fingers, matcha mascarpone, freeze-dried strawberry snow.',
    ar_desc:'صمّمها ضيف في استوديو الكيك فأدخلناها القائمة: أصابع سيدة منقوعة ببودرة الفراولة، وماسكاربوني الماتشا، وثلج الفراولة المجففة.' },
  { id:'c-basque', name:'Basque Burnt Cheesecake', ar_name:'تشيز كيك باسك المحروق', cat:'cake', price:2.100, whole:15.000, c1:'#e0bb84', c2:'#4b2a12',
    desc:'Baked hot and fast until the top goes almost black. Custardy centre, no crust, no apologies.',
    ar_desc:'تُخبز على حرارة عالية وسريعة حتى يكاد سطحها يسودّ. قلب كاسترد، بلا قاعدة، وبلا اعتذار.' },
  { id:'c-pistachio', name:'Pistachio Rose Layer Cake', ar_name:'كيك طبقات الفستق والورد', cat:'cake', price:2.400, whole:21.000, c1:'#cfd6a0', c2:'#8b9a52',
    desc:'Pistachio frangipane sponge, rose-water syrup, whipped white chocolate ganache.',
    ar_desc:'كيك فرانجيبان الفستق، وشراب ماء الورد، وغاناش الشوكولاتة البيضاء المخفوق.' },
  { id:'c-olive', name:'Olive Oil & Citrus Cake', ar_name:'كيك زيت الزيتون والحمضيات', cat:'cake', price:1.950, whole:13.500, c1:'#e8d79a', c2:'#a58a34',
    tag:'Vegan', ar_tag:'نباتي', tagClass:'tag-sage',
    desc:'Blood orange, good Sicilian oil, a crackle of demerara. Somehow better on day two.',
    ar_desc:'برتقال أحمر وزيت صقلي جيد وطبقة سكر ديميرارا مقرمشة. ألذ في اليوم الثاني.' },
  { id:'c-black', name:'Blackout Chocolate Cake', ar_name:'كيك الشوكولاتة المعتم', cat:'cake', price:2.400, whole:19.500, c1:'#5a3520', c2:'#1b0d06',
    desc:'Four layers of devil’s food, Guanaja ganache, and a mirror glaze that shows your reflection.',
    ar_desc:'أربع طبقات من كيك الشيطان، وغاناش غواناخا، وتزجيج مرآوي يعكس صورتك.' },
  { id:'c-lemon', name:'Lemon Meringue Tart', ar_name:'تارت الليمون بالمرينغ', cat:'cake', price:2.100, whole:14.500, c1:'#f0d783', c2:'#c79a2c',
    desc:'Sharp enough to make you blink, torched to order at the counter.',
    ar_desc:'حامضة لدرجة تجعلك ترمش، وتُحرق بالشعلة عند الطلب.' },
];

/* ==========================================================================
   STUDIO — Drink builder
   ========================================================================== */
const DRINK_OPTS = {
  temp:[
    { id:'iced',  name:'Iced',         ar_name:'مثلج',        sub:'Over cubed ice',  ar_sub:'على مكعبات الثلج', price:0 },
    { id:'hot',   name:'Hot',          ar_name:'ساخن',        sub:'Steamed to 60°C', ar_sub:'مبخّر إلى ٦٠°',    price:0 },
    { id:'nitro', name:'Nitro-tapped', ar_name:'نيترو',       sub:'Nitrogen pour',   ar_sub:'سكب بالنيتروجين',  price:.250 },
  ],
  size:[
    { id:'12', name:'12 oz', ar_name:'١٢ أونصة', sub:'Small',   ar_sub:'صغير',  price:0,    scale:.82 },
    { id:'16', name:'16 oz', ar_name:'١٦ أونصة', sub:'Regular', ar_sub:'وسط',   price:.200, scale:1 },
    { id:'20', name:'20 oz', ar_name:'٢٠ أونصة', sub:'Large',   ar_sub:'كبير',  price:.400, scale:1.16 },
  ],
  base:[
    { id:'espresso',  name:'Double Espresso',    ar_name:'إسبريسو مزدوج',   sub:'Bakehouse blend',    ar_sub:'خلطة المخبز',      price:0,    color:'#3c2110' },
    { id:'nitrocb',   name:'Nitro Cold Brew',    ar_name:'نيترو كولد برو',  sub:'From the tap',       ar_sub:'من الصنبور',       price:.200, color:'#33200f' },
    { id:'filter',    name:'Batch Filter',       ar_name:'قهوة مقطّرة',      sub:'Yirgacheffe',        ar_sub:'يرغاتشيفي',        price:0,    color:'#7a4c26' },
    { id:'qahwa',     name:'Arabic Qahwa',       ar_name:'قهوة عربية',      sub:'Cardamom & saffron', ar_sub:'هيل وزعفران',      price:.150, color:'#d0ae78' },
    { id:'matcha',    name:'Ceremonial Matcha',  ar_name:'ماتشا احتفالية',  sub:'Uji, first harvest', ar_sub:'أوجي، أول حصاد',   price:.350, color:'#7ea24f' },
    { id:'hojicha',   name:'Hojicha',            ar_name:'هوجيتشا',         sub:'Roasted green tea',  ar_sub:'شاي أخضر محمّص',    price:.200, color:'#9e6b3f' },
    { id:'chai',      name:'Masala Chai',        ar_name:'شاي ماسالا',      sub:'House-steeped',      ar_sub:'منقوع بيتياً',      price:.200, color:'#a86c40' },
    { id:'chocolate', name:'Drinking Chocolate', ar_name:'شوكولاتة سائلة',  sub:'Guanaja 70%',        ar_sub:'غواناخا ٧٠٪',      price:.250, color:'#4d2a17' },
    { id:'strawberry',name:'Strawberry Powder',  ar_name:'بودرة الفراولة',  sub:'Pure freeze-dried',  ar_sub:'مجففة بالتجميد',   price:.250, color:'#d4586a' },
    { id:'butterfly', name:'Butterfly Pea',      ar_name:'زهرة البازلاء',   sub:'Colour-shifting',    ar_sub:'تغيّر لونها',       price:.250, color:'#5c6bb0' },
    { id:'decaf',     name:'Decaf Espresso',     ar_name:'إسبريسو ديكاف',   sub:'Sugarcane process',  ar_sub:'بطريقة قصب السكر', price:0,    color:'#4a2a15' },
  ],
  milk:[
    { id:'whole',    name:'Whole Milk',  ar_name:'حليب كامل الدسم', sub:'Local, cream-line', ar_sub:'محلي، بالقشدة',  price:0,    color:'#fdf6e8' },
    { id:'oat',      name:'Oat',         ar_name:'شوفان',           sub:'Barista edition',   ar_sub:'نسخة الباريستا', price:.200, color:'#f2e3c9' },
    { id:'almond',   name:'Almond',      ar_name:'لوز',             sub:'Unsweetened',       ar_sub:'بدون سكر',       price:.200, color:'#f6ecd9' },
    { id:'pistachio',name:'Pistachio',   ar_name:'فستق',            sub:'House-made',        ar_sub:'بيتي الصنع',     price:.350, color:'#e6ecc4' },
    { id:'coconut',  name:'Coconut',     ar_name:'جوز الهند',       sub:'Full fat',          ar_sub:'كامل الدسم',     price:.200, color:'#fdfaf2' },
    { id:'camel',    name:'Camel Milk',  ar_name:'حليب الإبل',      sub:'Local dairy',       ar_sub:'من مزرعة محلية', price:.400, color:'#fcf6ea' },
    { id:'halfhalf', name:'Half & Half', ar_name:'نصف ونصف',        sub:'Extra rich',        ar_sub:'أكثر غنى',       price:.150, color:'#fcf2df' },
    { id:'none',     name:'No Milk',     ar_name:'بدون حليب',       sub:'Black / clear',     ar_sub:'سادة',           price:0,    color:null },
  ],
  syrup:[
    { id:'cinnsugar', name:'Cinnamon Sugar',      ar_name:'قرفة وسكر',        price:.200, color:'#c08c4f' },
    { id:'banana',    name:'Caramelised Banana',  ar_name:'موز مكرمل',        price:.200, color:'#d9b160' },
    { id:'raspchoc',  name:'Raspberry Choc Chip', ar_name:'توت وشوكولاتة',    price:.250, color:'#b1566e' },
    { id:'blueberry', name:'Wild Blueberry',      ar_name:'توت أزرق بري',     price:.200, color:'#7f76b8' },
    { id:'ginger',    name:'Ginger Citrus',       ar_name:'زنجبيل وحمضيات',   price:.200, color:'#dda85c' },
    { id:'lavender',  name:'Lavender Honey',      ar_name:'خزامى بالعسل',     price:.250, color:'#b3a1c6' },
    { id:'cherryvan', name:'Cherry Vanilla',      ar_name:'كرز وفانيلا',      price:.200, color:'#c26a63' },
    { id:'brownbut',  name:'Brown Butter',        ar_name:'زبدة بنية',        price:.250, color:'#c69a63' },
    { id:'orange',    name:'Orange Blossom',      ar_name:'ماء الزهر',        price:.200, color:'#e0b06a' },
    { id:'maple',     name:'Maple Pecan',         ar_name:'قيقب وبيكان',      price:.250, color:'#b57a41' },
    { id:'rose',      name:'Rose Cardamom',       ar_name:'ورد وهيل',         price:.250, color:'#d59aa6' },
    { id:'date',      name:'Salted Date',         ar_name:'تمر مملّح',         price:.250, color:'#96603a' },
    { id:'saffron',   name:'Saffron Honey',       ar_name:'زعفران بالعسل',    price:.300, color:'#e0b25c' },
    { id:'strawsyr',  name:'Strawberry',          ar_name:'فراولة',           price:.200, color:'#d9647a' },
    { id:'hazelnut',  name:'Toasted Hazelnut',    ar_name:'بندق محمّص',        price:.200, color:'#a9764a' },
  ],
  extra:[
    { id:'shot',      name:'Extra Shot',      ar_name:'جرعة إضافية',    sub:'+1 espresso',    ar_sub:'إسبريسو إضافي', price:.250, color:'#3c2110' },
    { id:'coldfoam',  name:'Cold Foam',       ar_name:'رغوة باردة',     sub:'Salted, silky',  ar_sub:'مملّحة وحريرية',  price:.300, color:'#fbf3e4', foam:true },
    { id:'strawfoam', name:'Strawberry Foam', ar_name:'رغوة الفراولة',  sub:'Pink cloud',     ar_sub:'سحابة وردية',   price:.350, color:'#f2b9c0', foam:true },
    { id:'matchafoam',name:'Matcha Foam',     ar_name:'رغوة الماتشا',   sub:'Whisked cap',    ar_sub:'قبعة مخفوقة',   price:.350, color:'#b8cf8c', foam:true },
    { id:'sweetcream',name:'Sweet Cream',     ar_name:'كريمة حلوة',     sub:'Vanilla bean',   ar_sub:'بعود الفانيلا',  price:.300, color:'#f7e9cf', foam:true },
    { id:'whip',      name:'Whipped Cream',   ar_name:'كريمة مخفوقة',   sub:'Lightly sweet',  ar_sub:'حلاوة خفيفة',   price:.300, color:'#fffaf0', foam:true },
    { id:'tonic',     name:'Tonic Water',     ar_name:'ماء فوّار',       sub:'Fever-Tree',     ar_sub:'فيفر تري',      price:.300, color:'#e8ecd8' },
    { id:'nitrofloat',name:'Nitro Float',     ar_name:'طفو النيترو',    sub:'Cascading top',  ar_sub:'قمة متدرّجة',    price:.400, color:'#c8a882', foam:true },
    { id:'seasalt',   name:'Sea Salt',        ar_name:'ملح بحري',       sub:'Flaky finish',   ar_sub:'رقائق ختامية',  price:0,    color:'#f0f0ec' },
  ],
  finish:[
    { id:'f-cinn',    name:'Cinnamon Sugar',    ar_name:'قرفة وسكر',        price:0,    color:'#b4813f' },
    { id:'f-cocoa',   name:'Dutch Cocoa',       ar_name:'كاكاو هولندي',     price:0,    color:'#5d3520' },
    { id:'f-matcha',  name:'Matcha Dust',       ar_name:'غبار الماتشا',     price:.150, color:'#7d9c4e' },
    { id:'f-straw',   name:'Strawberry Snow',   ar_name:'ثلج الفراولة',     price:.200, color:'#d9566c' },
    { id:'f-pist',    name:'Pistachio Crumb',   ar_name:'فتات الفستق',      price:.200, color:'#8fa456' },
    { id:'f-coconut', name:'Toasted Coconut',   ar_name:'جوز هند محمّص',     price:.150, color:'#dcc39a' },
    { id:'f-wafer',   name:'Wafer Crumble',     ar_name:'فتات الويفر',      price:.200, color:'#c39a5f' },
    { id:'f-honey',   name:'Honey Drizzle',     ar_name:'خيوط العسل',       price:.150, color:'#d9a441', drizzle:true },
    { id:'f-caramel', name:'Caramel Drizzle',   ar_name:'خيوط الكراميل',    price:.150, color:'#a8672c', drizzle:true },
    { id:'f-date',    name:'Date Syrup Drizzle',ar_name:'خيوط دبس التمر',   price:.150, color:'#8a5424', drizzle:true },
    { id:'f-choc',    name:'Chocolate Shards',  ar_name:'شظايا الشوكولاتة', price:.200, color:'#3f2313' },
    { id:'f-saffron', name:'Saffron Threads',   ar_name:'خيوط الزعفران',    price:.300, color:'#d98a2b' },
    { id:'f-flower',  name:'Dried Rose Petals', ar_name:'بتلات ورد مجففة',  price:.200, color:'#c98a95' },
  ],
};

/* ==========================================================================
   STUDIO — Cake builder
   ========================================================================== */
const CAKE_OPTS = {
  format:[
    { id:'slice', name:'Single Slice',  ar_name:'قطعة واحدة',  sub:'Eat it here',    ar_sub:'تُؤكل هنا',      price:2.500,  serves:'1',     ar_serves:'١',       w:.42 },
    { id:'6in',   name:'6 inch',        ar_name:'٦ إنش',       sub:'Small round',    ar_sub:'دائرية صغيرة',  price:15.000, serves:'6–8',   ar_serves:'٦–٨',    w:.72 },
    { id:'8in',   name:'8 inch',        ar_name:'٨ إنش',       sub:'Classic round',  ar_sub:'دائرية كلاسيكية',price:21.000,serves:'12–16', ar_serves:'١٢–١٦',  w:.88 },
    { id:'10in',  name:'10 inch',       ar_name:'١٠ إنش',      sub:'Celebration',    ar_sub:'للمناسبات',     price:28.000, serves:'20–25', ar_serves:'٢٠–٢٥',  w:1 },
    { id:'sheet', name:'Quarter Sheet', ar_name:'صينية ربع',   sub:'Feeds the room', ar_sub:'تكفي المجلس',   price:25.000, serves:'24–30', ar_serves:'٢٤–٣٠',  w:1 },
  ],
  sponge:[
    { id:'vanilla',   name:'Vanilla Chiffon',      ar_name:'شيفون الفانيلا',   sub:'Light, airy',         ar_sub:'خفيف وهوائي',    price:0,     color:'#f2e3c2' },
    { id:'chocolate', name:'Devil’s Food',         ar_name:'كيك الشيطان',      sub:'Dark, damp',          ar_sub:'داكن ورطب',      price:.600,  color:'#4e2e1c' },
    { id:'ladyfinger',name:'Lady Fingers',         ar_name:'أصابع السيدة',     sub:'Savoiardi, soakable', ar_sub:'سافوياردي تمتص', price:.900,  color:'#e9d3a5' },
    { id:'matcha',    name:'Matcha Sponge',        ar_name:'كيك الماتشا',      sub:'Uji culinary',        ar_sub:'ماتشا أوجي',     price:1.200, color:'#a8c179' },
    { id:'pistachio', name:'Pistachio Frangipane', ar_name:'فرانجيبان الفستق', sub:'Bronte paste',        ar_sub:'معجون برونتي',   price:1.500, color:'#c2cf8d' },
    { id:'oliveoil',  name:'Olive Oil Cake',       ar_name:'كيك زيت الزيتون',  sub:'Citrus, vegan',       ar_sub:'حمضي ونباتي',    price:.900,  color:'#eeda9c' },
    { id:'date',      name:'Date & Cardamom',      ar_name:'التمر والهيل',     sub:'Sticky, spiced',      ar_sub:'دبق ومبهّر',      price:1.200, color:'#c08d58' },
    { id:'redvelvet', name:'Red Velvet',           ar_name:'ريد فيلفيت',       sub:'Buttermilk, cocoa',   ar_sub:'لبن وكاكاو',     price:.900,  color:'#a63d34' },
    { id:'basque',    name:'Basque Burnt Custard', ar_name:'كاسترد باسك',      sub:'No layers, all top',  ar_sub:'بلا طبقات',      price:1.200, color:'#dfb478' },
    { id:'dacquoise', name:'Almond Dacquoise',     ar_name:'داكواز اللوز',     sub:'Crisp meringue',      ar_sub:'مرينغ مقرمش',    price:1.200, color:'#e8d9b6' },
    { id:'ube',       name:'Ube Chiffon',          ar_name:'شيفون الأوبي',     sub:'Purple yam',          ar_sub:'بطاطا أرجوانية', price:1.500, color:'#a08cc4' },
  ],
  soak:[
    { id:'none',       name:'No Soak',            ar_name:'بدون نقع',        sub:'Keep it dry',            ar_sub:'اتركها جافة',      price:0,     color:null },
    { id:'espresso',   name:'Espresso',           ar_name:'إسبريسو',         sub:'The tiramisù classic',   ar_sub:'كلاسيكية التيراميسو',price:.600, color:'#4a2a14' },
    { id:'strawmatcha',name:'Strawberry + Matcha',ar_name:'فراولة + ماتشا',  sub:'Powder-bloomed',         ar_sub:'بودرة منقوعة',     price:1.200, color:'#c9748a' },
    { id:'rose',       name:'Rose Water',         ar_name:'ماء الورد',       sub:'Delicate, floral',       ar_sub:'رقيق وزهري',       price:.900,  color:'#dba9b4' },
    { id:'saffron',    name:'Saffron & Honey',    ar_name:'زعفران وعسل',     sub:'Warm, golden',           ar_sub:'دافئ وذهبي',       price:1.200, color:'#e0b25c' },
    { id:'almond',     name:'Toasted Almond',     ar_name:'لوز محمّص',        sub:'Alcohol-free amaretto',  ar_sub:'أماريتو بلا كحول', price:.900,  color:'#c9a066' },
    { id:'ginger',     name:'Ginger Citrus',      ar_name:'زنجبيل وحمضيات',  sub:'Sharp and warm',         ar_sub:'حاد ودافئ',        price:.900,  color:'#dfa957' },
    { id:'caramel',    name:'Salted Date Caramel',ar_name:'كراميل التمر',    sub:'Sticky, deep',           ar_sub:'دبق وعميق',        price:.900,  color:'#a06a2f' },
    { id:'hojicha',    name:'Hojicha',            ar_name:'هوجيتشا',         sub:'Roasted, smoky',         ar_sub:'محمّص ومدخّن',       price:.900,  color:'#a4703f' },
  ],
  filling:[
    { id:'mascarpone', name:'Mascarpone Cream',   ar_name:'كريمة ماسكاربوني', price:1.100, color:'#f7edd8' },
    { id:'matchacream',name:'Matcha Cream',       ar_name:'كريمة الماتشا',    price:1.400, color:'#b9cf8e' },
    { id:'strawcomp',  name:'Strawberry Compote', ar_name:'كومبوت الفراولة',  price:1.100, color:'#cf5f6d' },
    { id:'pistcream',  name:'Pistachio Cream',    ar_name:'كريمة الفستق',     price:1.700, color:'#bcca85' },
    { id:'ganache',    name:'Dark Ganache',       ar_name:'غاناش داكن',       price:1.400, color:'#3f2415' },
    { id:'lemoncurd',  name:'Lemon Curd',         ar_name:'كريمة الليمون',    price:1.100, color:'#efd270' },
    { id:'ricotta',    name:'Whipped Ricotta',    ar_name:'ريكوتا مخفوقة',    price:1.100, color:'#f9f2e3' },
    { id:'saltcaramel',name:'Salted Date Caramel',ar_name:'كراميل التمر',     price:1.100, color:'#b57736' },
    { id:'blueberry',  name:'Blueberry Jam',      ar_name:'مربى التوت الأزرق',price:1.100, color:'#7d6faa' },
    { id:'custard',    name:'Cinnamon Custard',   ar_name:'كاسترد القرفة',    price:1.100, color:'#efd9a6' },
    { id:'dulcey',     name:'Dulcey Blond Cream', ar_name:'كريمة دولسي',      price:1.400, color:'#d8ab6a' },
    { id:'rosecream',  name:'Rose Chantilly',     ar_name:'شانتيه الورد',     price:1.400, color:'#eec3ca' },
  ],
  exterior:[
    { id:'naked',      name:'Naked',               ar_name:'مكشوف',          sub:'Layers on show',    ar_sub:'الطبقات ظاهرة',  price:0,     color:null },
    { id:'swiss',      name:'Swiss Meringue',      ar_name:'مرينغ سويسري',   sub:'Silky, sculptable', ar_sub:'حريري وقابل للتشكيل',price:1.700,color:'#fbf4e6' },
    { id:'mascfrost',  name:'Mascarpone Frosting', ar_name:'فروستنغ ماسكاربوني',sub:'Tangy, soft',    ar_sub:'حامض وطري',      price:1.700, color:'#f6ead4' },
    { id:'ganachedrip',name:'Ganache Drip',        ar_name:'تقطير الغاناش',  sub:'Down the sides',    ar_sub:'ينزل على الجوانب',price:2.000, color:'#3a2113', drip:true },
    { id:'matchaglaze',name:'Matcha Glaze',        ar_name:'تزجيج الماتشا',  sub:'Mirror finish',     ar_sub:'لمعة مرآوية',    price:2.000, color:'#8fae5e', drip:true },
    { id:'cocoadust',  name:'Cocoa Dust',          ar_name:'غبار الكاكاو',   sub:'Tiramisù finish',   ar_sub:'ختام التيراميسو',price:.900,  color:'#6a4126', dust:true },
    { id:'pistdust',   name:'Pistachio Dust',      ar_name:'غبار الفستق',    sub:'Green and fine',    ar_sub:'أخضر وناعم',     price:1.100, color:'#7f9448', dust:true },
    { id:'whipped',    name:'Whipped Cream',       ar_name:'كريمة مخفوقة',   sub:'Cloud-light',       ar_sub:'خفيفة كالسحاب',  price:1.400, color:'#fffbf2' },
    { id:'strawglaze', name:'Strawberry Glaze',    ar_name:'تزجيج الفراولة', sub:'Glossy pink',       ar_sub:'وردي لامع',      price:2.000, color:'#d76a7c', drip:true },
  ],
  garnish:[
    { id:'g-straw',   name:'Fresh Strawberries',   ar_name:'فراولة طازجة',      price:1.100, color:'#c8404f', shape:'berry' },
    { id:'g-fdstraw', name:'Strawberry Snow',      ar_name:'ثلج الفراولة',      price:.900,  color:'#e0748a', shape:'dust' },
    { id:'g-matcha',  name:'Matcha Dust',          ar_name:'غبار الماتشا',      price:.600,  color:'#7fa14f', shape:'dust' },
    { id:'g-pist',    name:'Pistachio Crumb',      ar_name:'فتات الفستق',       price:.900,  color:'#8ea456', shape:'crumb' },
    { id:'g-gold',    name:'23k Gold Leaf',        ar_name:'ورق ذهب ٢٣ قيراط',  price:3.500, color:'#e0bc55', shape:'leaf' },
    { id:'g-curls',   name:'Chocolate Curls',      ar_name:'لفائف الشوكولاتة',  price:.900,  color:'#3d2213', shape:'curl' },
    { id:'g-flowers', name:'Edible Flowers',       ar_name:'زهور صالحة للأكل',  price:1.700, color:'#d78fa0', shape:'flower' },
    { id:'g-meringue',name:'Torched Meringue',     ar_name:'مرينغ محروق',       price:1.100, color:'#f2e4c6', shape:'blob' },
    { id:'g-beans',   name:'Espresso Beans',       ar_name:'حبوب إسبريسو',      price:.600,  color:'#3a1f0e', shape:'bean' },
    { id:'g-dates',   name:'Glazed Date Halves',   ar_name:'أنصاف تمر ملمّعة',   price:1.100, color:'#8a5a2c', shape:'berry' },
    { id:'g-brulee',  name:'Brûléed Sugar Shards', ar_name:'شظايا سكر محروق',   price:.900,  color:'#c99248', shape:'shard' },
  ],
};

/* ==========================================================================
   STUDIO — Cookie builder
   Shapes are SVG paths in a 100×100 box, applied as a CSS mask so they
   scale cleanly and clip the dough, the icing and the texture together.
   ========================================================================== */
function scallopPath(bumps = 12, r = 40, br = 8) {
  const pts = [];
  for (let i = 0; i < bumps; i++) {
    const a = (i / bumps) * Math.PI * 2 - Math.PI / 2;
    pts.push([50 + Math.cos(a) * r, 50 + Math.sin(a) * r]);
  }
  let d = `M${pts[0][0].toFixed(1)} ${pts[0][1].toFixed(1)}`;
  for (let i = 1; i <= bumps; i++) {
    const p = pts[i % bumps];
    d += ` A${br} ${br} 0 0 1 ${p[0].toFixed(1)} ${p[1].toFixed(1)}`;
  }
  return d + ' Z';
}

const COOKIE_OPTS = {
  pack:[
    { id:'one',   name:'Just the one', ar_name:'واحدة فقط',      sub:'Try the design',   ar_sub:'جرّب التصميم', price:.750,  qty:1 },
    { id:'six',   name:'Box of six',   ar_name:'علبة من ست',     sub:'Same design ×6',   ar_sub:'نفس التصميم ×٦', price:4.250, qty:6 },
    { id:'twelve',name:'Box of twelve',ar_name:'علبة من اثنتي عشرة', sub:'Gift-ribboned', ar_sub:'بشريطة هدية',  price:8.000, qty:12 },
  ],
  size:[
    { id:'sm', name:'7 cm',  ar_name:'٧ سم',  sub:'Bite-size',  ar_sub:'لقمة',      price:0,    scale:.76 },
    { id:'md', name:'10 cm', ar_name:'١٠ سم', sub:'Standard',   ar_sub:'قياسي',     price:.250, scale:1 },
    { id:'lg', name:'14 cm', ar_name:'١٤ سم', sub:'Plaque-size',ar_sub:'حجم اللوح', price:.500, scale:1.2 },
  ],
  shape:[
    { id:'round',    name:'Round',     ar_name:'دائرية',  price:0,    path:'M50 3 A47 47 0 1 1 49.9 3 Z' },
    { id:'plaque',   name:'Plaque',    ar_name:'لوح',     price:0,    path:'M14 5 H86 A9 9 0 0 1 95 14 V86 A9 9 0 0 1 86 95 H14 A9 9 0 0 1 5 86 V14 A9 9 0 0 1 14 5 Z' },
    { id:'scallop',  name:'Scalloped', ar_name:'مموّجة',   price:.100, path:scallopPath(12, 42, 9) },
    { id:'heart',    name:'Heart',     ar_name:'قلب',     price:.100, path:'M50 93 C17 70 5 51 5 34 C5 17 18 7 31 7 C41 7 47 13 50 21 C53 13 59 7 69 7 C82 7 95 17 95 34 C95 51 83 70 50 93 Z' },
    { id:'star',     name:'Star',      ar_name:'نجمة',    price:.100, path:'M50 4 L61 36 L95 36 L67 56 L78 90 L50 70 L22 90 L33 56 L5 36 L39 36 Z' },
    { id:'crescent', name:'Crescent',  ar_name:'هلال',    price:.150, path:'M64 5 A47 47 0 1 0 64 95 A38 38 0 1 1 64 5 Z' },
    { id:'hexagon',  name:'Hexagon',   ar_name:'سداسية',  price:.100, path:'M50 3 L92 27 L92 73 L50 97 L8 73 L8 27 Z' },
    { id:'arch',     name:'Arch',      ar_name:'قوس',     price:.100, path:'M8 96 L8 42 A42 42 0 0 1 92 42 L92 96 Z' },
  ],
  dough:[
    { id:'sugar',     name:'Vanilla Sugar',    ar_name:'فانيلا وسكر',   sub:'The classic canvas',  ar_sub:'اللوحة الكلاسيكية', price:0,    color:'#e8cd9c' },
    { id:'choc',      name:'Dark Chocolate',   ar_name:'شوكولاتة داكنة',sub:'Cocoa-heavy',         ar_sub:'غني بالكاكاو',      price:.150, color:'#6b4227' },
    { id:'gingerbread',name:'Gingerbread',     ar_name:'خبز الزنجبيل',  sub:'Molasses, spice',     ar_sub:'دبس وبهار',         price:.150, color:'#c08a4c' },
    { id:'brownbutter',name:'Brown Butter',    ar_name:'زبدة بنية',     sub:'Nutty, deep',         ar_sub:'بطعم الجوز',        price:.150, color:'#d3a869' },
    { id:'datecard',  name:'Date & Cardamom',  ar_name:'تمر وهيل',      sub:'Local favourite',     ar_sub:'المفضّل محلياً',      price:.250, color:'#c18a52' },
    { id:'pistachio', name:'Pistachio',        ar_name:'فستق',          sub:'Bronte paste',        ar_sub:'معجون برونتي',      price:.250, color:'#c6cf94' },
    { id:'lemon',     name:'Lemon Poppyseed',  ar_name:'ليمون وخشخاش',  sub:'Bright, speckled',    ar_sub:'منعش ومنقّط',        price:.150, color:'#eddba0' },
    { id:'redvelvet', name:'Red Velvet',       ar_name:'ريد فيلفيت',    sub:'Cocoa, buttermilk',   ar_sub:'كاكاو ولبن',        price:.150, color:'#b04c40' },
  ],
  icing:[
    { id:'none',     name:'No Icing',      ar_name:'بدون آيسنغ',  sub:'Bare dough',     ar_sub:'عجينة عارية',  price:0,    color:null },
    { id:'white',    name:'Royal White',   ar_name:'أبيض ملكي',   sub:'The blank page', ar_sub:'الصفحة البيضاء',price:.150, color:'#FFFBF2' },
    { id:'cream',    name:'Cream',         ar_name:'كريمي',       sub:'House cream',    ar_sub:'كريمي البيت',   price:.150, color:'#FDF7E4' },
    { id:'sand',     name:'Warm Sand',     ar_name:'رملي دافئ',   sub:'Soft neutral',   ar_sub:'محايد ناعم',    price:.150, color:'#DED0B6' },
    { id:'toffee',   name:'Toffee',        ar_name:'توفي',        sub:'House brown',    ar_sub:'بني البيت',     price:.150, color:'#B8794B' },
    { id:'espresso', name:'Espresso',      ar_name:'إسبريسو',     sub:'Nearly black',   ar_sub:'يكاد يكون أسود',price:.150, color:'#4C2D1F' },
    { id:'blush',    name:'Blush Pink',    ar_name:'وردي خفيف',   sub:'Strawberry',     ar_sub:'فراولة',        price:.200, color:'#EEBFC2' },
    { id:'sage',     name:'Sage',          ar_name:'مريمية',      sub:'Matcha-tinted',  ar_sub:'بلون الماتشا',  price:.200, color:'#B7C39A' },
    { id:'saffron',  name:'Saffron Gold',  ar_name:'ذهبي زعفراني',sub:'Warm yellow',    ar_sub:'أصفر دافئ',     price:.200, color:'#E3B45E' },
    { id:'rose',     name:'Dusty Rose',    ar_name:'وردي باهت',   sub:'Deeper pink',    ar_sub:'وردي أعمق',     price:.200, color:'#C98A95' },
  ],
  font:[
    { id:'script',   name:'Flowing Script',  ar_name:'خط انسيابي',   family:"'Great Vibes', cursive",      sample:'Mabrouk', ar_sample:'مبروك', latin:true,  arabic:false, weight:'400', lh:1.15, scale:1.35 },
    { id:'classic',  name:'Classic Serif',   ar_name:'رقعي كلاسيكي', family:"'Playfair Display', serif",   sample:'Mabrouk', ar_sample:'مبروك', latin:true,  arabic:false, weight:'600', lh:1.12, scale:1 },
    { id:'bold',     name:'Tall Capitals',   ar_name:'حروف طويلة',   family:"'Bebas Neue', sans-serif",    sample:'MABROUK', ar_sample:'مبروك', latin:true,  arabic:false, weight:'400', lh:1,    scale:1.15 },
    { id:'hand',     name:'Handwritten',     ar_name:'خط اليد',      family:"'Caveat', cursive",           sample:'Mabrouk', ar_sample:'مبروك', latin:true,  arabic:false, weight:'600', lh:1.1,  scale:1.25 },
    { id:'engraved', name:'Engraved Caps',   ar_name:'حروف محفورة',  family:"'Cinzel', serif",             sample:'MABROUK', ar_sample:'مبروك', latin:true,  arabic:false, weight:'600', lh:1.2,  scale:.95 },
    { id:'retro',    name:'Retro Round',     ar_name:'مستدير قديم',  family:"'Pacifico', cursive",         sample:'Mabrouk', ar_sample:'مبروك', latin:true,  arabic:false, weight:'400', lh:1.25, scale:1.05 },
    { id:'naskh',    name:'Amiri Naskh',     ar_name:'أميري نسخ',    family:"'Amiri', serif",              sample:'Mabrouk', ar_sample:'مبروك', latin:true,  arabic:true,  weight:'700', lh:1.5,  scale:1.1 },
    { id:'kufi',     name:'Reem Kufi',       ar_name:'ريم كوفي',     family:"'Reem Kufi', sans-serif",     sample:'Mabrouk', ar_sample:'مبروك', latin:false, arabic:true,  weight:'600', lh:1.45, scale:1 },
    { id:'ruqaa',    name:'Aref Ruqaa',      ar_name:'عارف رقعة',    family:"'Aref Ruqaa', serif",         sample:'Mabrouk', ar_sample:'مبروك', latin:false, arabic:true,  weight:'700', lh:1.6,  scale:1.1 },
  ],
  decor:[
    { id:'x-sprinkle', name:'Rainbow Sprinkles', ar_name:'رشّات ملوّنة',      price:.100, color:'#D98A9B', shape:'sprinkle' },
    { id:'x-sanding',  name:'Sanding Sugar',     ar_name:'سكر رملي',         price:.100, color:'#F3E4C4', shape:'dust' },
    { id:'x-pearl',    name:'Pearl Dragées',     ar_name:'حبيبات لؤلؤية',    price:.200, color:'#E8E0D0', shape:'pearl' },
    { id:'x-gold',     name:'23k Gold Leaf',     ar_name:'ورق ذهب ٢٣ قيراط', price:1.500, color:'#E0BC55', shape:'leaf' },
    { id:'x-rose',     name:'Dried Rose Petals', ar_name:'بتلات ورد مجففة',  price:.300, color:'#C98A95', shape:'petal' },
    { id:'x-pist',     name:'Pistachio Crumb',   ar_name:'فتات الفستق',      price:.250, color:'#8EA456', shape:'crumb' },
    { id:'x-straw',    name:'Strawberry Snow',   ar_name:'ثلج الفراولة',     price:.250, color:'#E0748A', shape:'dust' },
    { id:'x-drizzle',  name:'Chocolate Drizzle', ar_name:'خيوط الشوكولاتة',  price:.200, color:'#4A2A17', shape:'drizzle' },
    { id:'x-border',   name:'Piped Border',      ar_name:'إطار مزخرف',       price:.250, color:'#FFFBF2', shape:'border' },
    { id:'x-glitter',  name:'Edible Glitter',    ar_name:'بريق صالح للأكل',  price:.300, color:'#EBD9A8', shape:'glitter' },
  ],
};

/* ------------------------------------------------------------- PRESETS */
const DRINK_PRESETS = [
  { name:'Strawberry Matcha Cloud', ar_name:'سحابة الفراولة والماتشا',
    blurb:'The one everyone photographs.', ar_blurb:'المشروب الذي يصوّره الجميع.',
    state:{ temp:'iced', size:'16', base:'matcha', milk:'oat', syrups:{ strawsyr:2 }, extras:['strawfoam'], finishes:['f-straw'] } },
  { name:'Rose Cardamom Majlis', ar_name:'مجلس الورد والهيل',
    blurb:'Taif rose, green cardamom, whole milk.', ar_blurb:'ورد طائفي وهيل أخضر وحليب كامل الدسم.',
    state:{ temp:'hot', size:'12', base:'espresso', milk:'whole', syrups:{ rose:2 }, extras:[], finishes:['f-flower'] } },
  { name:'The Dirty Wafer', ar_name:'ذا دِرتي ويفر',
    blurb:'Dessert pretending to be a drink.', ar_blurb:'حلوى تتظاهر بأنها مشروب.',
    state:{ temp:'iced', size:'16', base:'chocolate', milk:'whole', syrups:{ hazelnut:2 }, extras:['shot','whip'], finishes:['f-wafer','f-caramel'] } },
  { name:'Salted Date Nitro', ar_name:'نيترو التمر المملّح',
    blurb:'Khalas dates, on tap.', ar_blurb:'تمر الخلاص، على الصنبور.',
    state:{ temp:'nitro', size:'16', base:'nitrocb', milk:'oat', syrups:{ date:2 }, extras:['sweetcream'], finishes:['f-date'] } },
  { name:'Saffron Qahwa Tonic', ar_name:'قهوة الزعفران الفوّارة',
    blurb:'Blonde qahwa over ice and tonic.', ar_blurb:'قهوة شقراء على الثلج والماء الفوار.',
    state:{ temp:'iced', size:'12', base:'qahwa', milk:'none', syrups:{ saffron:1 }, extras:['tonic'], finishes:['f-saffron'] } },
  { name:'Raspberry Chocolate Chip', ar_name:'توت أحمر بقطع الشوكولاتة',
    blurb:'Straight off the ice-cream truck.', ar_blurb:'مباشرة من عربة الآيس كريم.',
    state:{ temp:'iced', size:'16', base:'espresso', milk:'whole', syrups:{ raspchoc:3 }, extras:['coldfoam'], finishes:['f-choc'] } },
];

const CAKE_PRESETS = [
  { name:'Strawberry Matcha Tiramisù', ar_name:'تيراميسو الفراولة والماتشا',
    blurb:'Lady fingers soaked in strawberry powder and matcha instead of coffee.',
    ar_blurb:'أصابع سيدة منقوعة ببودرة الفراولة والماتشا بدل القهوة.',
    state:{ format:'6in', layers:4, sponge:'ladyfinger', soak:'strawmatcha',
      fillings:['mascarpone','matchacream','strawcomp'], exterior:'cocoadust',
      garnishes:['g-fdstraw','g-matcha','g-straw'], inscription:'' } },
  { name:'Saffron Date Celebration', ar_name:'احتفال الزعفران والتمر',
    blurb:'Date sponge, saffron honey soak, gold leaf.', ar_blurb:'كيك التمر، نقع الزعفران بالعسل، وورق ذهب.',
    state:{ format:'8in', layers:3, sponge:'date', soak:'saffron',
      fillings:['saltcaramel','mascarpone'], exterior:'mascfrost',
      garnishes:['g-dates','g-gold','g-pist'], inscription:'مبروك' } },
  { name:'Classic Espresso Tiramisù', ar_name:'تيراميسو الإسبريسو الكلاسيكي',
    blurb:'The original, exactly as it should be.', ar_blurb:'الأصل، تماماً كما ينبغي.',
    state:{ format:'slice', layers:4, sponge:'ladyfinger', soak:'espresso',
      fillings:['mascarpone'], exterior:'cocoadust', garnishes:['g-beans'], inscription:'' } },
  { name:'Pistachio Rose', ar_name:'الفستق والورد',
    blurb:'Bronte pistachio, rose chantilly, gold leaf.', ar_blurb:'فستق برونتي، شانتيه الورد، وورق ذهب.',
    state:{ format:'8in', layers:3, sponge:'pistachio', soak:'rose',
      fillings:['pistcream','rosecream'], exterior:'swiss',
      garnishes:['g-pist','g-flowers','g-gold'], inscription:'Congratulations' } },
  { name:'Blackout Ganache', ar_name:'غاناش الظلام',
    blurb:'Four layers of devil’s food and a drip.', ar_blurb:'أربع طبقات من كيك الشيطان مع تقطير.',
    state:{ format:'8in', layers:4, sponge:'chocolate', soak:'espresso',
      fillings:['ganache','saltcaramel'], exterior:'ganachedrip',
      garnishes:['g-curls','g-brulee'], inscription:'' } },
  { name:'Ube Coconut Dream', ar_name:'حلم الأوبي وجوز الهند',
    blurb:'Purple yam chiffon under torched meringue.', ar_blurb:'شيفون البطاطا الأرجوانية تحت مرينغ محروق.',
    state:{ format:'6in', layers:3, sponge:'ube', soak:'none',
      fillings:['ricotta','dulcey'], exterior:'whipped',
      garnishes:['g-meringue','g-flowers'], inscription:'' } },
];

const COOKIE_PRESETS = [
  { name:'Eid Crescent', ar_name:'هلال العيد',
    blurb:'Saffron icing, gold leaf, one word.', ar_blurb:'آيسنغ زعفراني، ورق ذهب، وكلمة واحدة.',
    state:{ pack:'six', size:'md', shape:'crescent', dough:'datecard', icing:'saffron',
      text:'عيدكم مبارك', font:'ruqaa', textColor:'#4C2D1F', textSize:15,
      decor:['x-gold','x-pist'] } },
  { name:'Mabrouk Plaque', ar_name:'لوح مبروك',
    blurb:'A blank white plaque and a flowing script.', ar_blurb:'لوح أبيض فارغ وخط انسيابي.',
    state:{ pack:'one', size:'lg', shape:'plaque', dough:'sugar', icing:'white',
      text:'Mabrouk', font:'script', textColor:'#B8794B', textSize:20,
      decor:['x-border','x-pearl'] } },
  { name:'Rose Heart', ar_name:'قلب الورد',
    blurb:'Dusty rose icing, petals, two initials.', ar_blurb:'آيسنغ وردي باهت، بتلات، وحرفان.',
    state:{ pack:'twelve', size:'md', shape:'heart', dough:'pistachio', icing:'rose',
      text:'W & N', font:'engraved', textColor:'#FFFBF2', textSize:17,
      decor:['x-rose','x-glitter'] } },
  { name:'Graduation Star', ar_name:'نجمة التخرج',
    blurb:'Espresso icing, tall capitals, gold.', ar_blurb:'آيسنغ إسبريسو، حروف طويلة، وذهب.',
    state:{ pack:'twelve', size:'md', shape:'star', dough:'choc', icing:'espresso',
      text:'CLASS OF 2026', font:'bold', textColor:'#E3B45E', textSize:13,
      decor:['x-gold','x-sanding'] } },
  { name:'Thank You Scallop', ar_name:'شكراً المموّجة',
    blurb:'Sage icing, handwriting, sprinkles.', ar_blurb:'آيسنغ مريمية، خط يد، ورشّات.',
    state:{ pack:'six', size:'md', shape:'scallop', dough:'lemon', icing:'sage',
      text:'Thank you', font:'hand', textColor:'#4C2D1F', textSize:18,
      decor:['x-sprinkle','x-border'] } },
  { name:'Ramadan Kareem', ar_name:'رمضان كريم',
    blurb:'Toffee icing, kufi lettering, pearls.', ar_blurb:'آيسنغ توفي، خط كوفي، ولآلئ.',
    state:{ pack:'twelve', size:'md', shape:'arch', dough:'gingerbread', icing:'toffee',
      text:'رمضان كريم', font:'kufi', textColor:'#FDF7E4', textSize:15,
      decor:['x-pearl','x-glitter'] } },
];

/* ============================================== RECIPE OF THE MONTH
   Guest-designed drinks and cakes we liked enough to put on the board.
   `state` loads straight back into the Studio so anyone can tweak it.   */
const MONTHLY_RECIPES = [
  {
    month:'September 2026', ar_month:'سبتمبر ٢٠٢٦', current:true,
    by:'Dana K., Zahra', ar_by:'دانة ك.، الزهراء',
    kind:'drink', mode:'drink',
    name:'Loomi Rose Cold Brew', ar_name:'كولد برو اللومي والورد',
    price:2.350, c1:'#e6b9be', c2:'#3a2114',
    story:'Dana built this on a Thursday afternoon and left without telling anyone. The barista who made it ordered one for herself, then put it on the specials board. Dried-lime brightness against rose and cold brew should not work. It does.',
    ar_story:'صمّمتها دانة عصر يوم خميس وخرجت دون أن تخبر أحداً. الباريستا التي حضّرتها طلبت واحدة لنفسها ثم كتبتها على لوح العروض. حموضة اللومي المجفف مع الورد والقهوة الباردة لا يُفترض أن تنجح، لكنها تنجح.',
    quote:'I wanted something that tasted like my grandmother’s kitchen but woke me up.',
    ar_quote:'أردت شيئاً بطعم مطبخ جدتي لكنه يوقظني.',
    recipeLines:['16 oz over ice','Nitro cold brew base','Oat milk','2 pumps rose cardamom','1 pump ginger citrus','Cold foam','Dried rose petals'],
    ar_recipeLines:['١٦ أونصة على الثلج','قاعدة نيترو كولد برو','حليب شوفان','ضخّتان ورد وهيل','ضخّة زنجبيل وحمضيات','رغوة باردة','بتلات ورد مجففة'],
    state:{ temp:'iced', size:'16', base:'nitrocb', milk:'oat',
      syrups:{ rose:2, ginger:1 }, extras:['coldfoam'], finishes:['f-flower'] },
  },
  {
    month:'August 2026', ar_month:'أغسطس ٢٠٢٦', current:false,
    by:'Yousef A., Jabriya', ar_by:'يوسف ع.، الجابرية',
    kind:'cake', mode:'cake',
    name:'Gahwa Tiramisù', ar_name:'تيراميسو الگهوة',
    price:19.500, c1:'#e3c79a', c2:'#8a5a2c',
    story:'Yousef swapped the espresso soak for cardamom-heavy Arabic qahwa and added glazed dates on top. Sold out in four days. We have made it eleven times since.',
    ar_story:'استبدل يوسف نقع الإسبريسو بقهوة عربية غنية بالهيل وأضاف تمراً ملمّعاً في الأعلى. نفدت خلال أربعة أيام، وصنعناها إحدى عشرة مرة منذ ذلك الحين.',
    quote:'Tiramisù is just a soaked biscuit. Ours has been soaked in qahwa for a thousand years.',
    ar_quote:'التيراميسو مجرد بسكويت منقوع. وبسكويتنا منقوع بالگهوة منذ ألف سنة.',
    recipeLines:['8 inch, 4 layers','Lady fingers','Saffron & honey soak','Mascarpone + date caramel','Cocoa dust','Glazed dates, gold leaf'],
    ar_recipeLines:['٨ إنش، ٤ طبقات','أصابع السيدة','نقع الزعفران والعسل','ماسكاربوني + كراميل التمر','غبار الكاكاو','تمر ملمّع وورق ذهب'],
    state:{ format:'8in', layers:4, sponge:'ladyfinger', soak:'saffron',
      fillings:['mascarpone','saltcaramel'], exterior:'cocoadust',
      garnishes:['g-dates','g-gold'], inscription:'' },
  },
  {
    month:'July 2026', ar_month:'يوليو ٢٠٢٦', current:false,
    by:'Mariam H., Kuwait City', ar_by:'مريم ح.، مدينة الكويت',
    kind:'drink', mode:'drink',
    name:'Pistachio Hojicha Float', ar_name:'طفو الفستق والهوجيتشا',
    price:2.450, c1:'#dfe0b4', c2:'#7a5030',
    story:'Roasted tea, pistachio milk and a nitro float. Mariam described it as "a bakery in a cup" and we have not found a better description.',
    ar_story:'شاي محمّص وحليب فستق وطفو نيترو. وصفتها مريم بأنها «مخبز في كوب»، ولم نجد وصفاً أفضل.',
    quote:'It tastes like the smell of this place at seven in the morning.',
    ar_quote:'طعمها كرائحة هذا المكان في السابعة صباحاً.',
    recipeLines:['16 oz over ice','Hojicha base','Pistachio milk','1 pump brown butter','Nitro float','Pistachio crumb'],
    ar_recipeLines:['١٦ أونصة على الثلج','قاعدة هوجيتشا','حليب فستق','ضخّة زبدة بنية','طفو نيترو','فتات الفستق'],
    state:{ temp:'iced', size:'16', base:'hojicha', milk:'pistachio',
      syrups:{ brownbut:1 }, extras:['nitrofloat'], finishes:['f-pist'] },
  },
];
